# Generated by Django 6.0.2 on 2026-02-25 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0002_doctor_gallery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='email',
        ),
    ]
